In [1]:
import sqlite3
import requests
import time
import json
import pandas as pd
import urllib.parse

from dotenv import load_dotenv
import os

from pathlib import Path

In [2]:
ROOT = Path.cwd().parent

In [3]:
load_dotenv(ROOT / '.env')

TWITCH_CLIENT_ID = os.getenv('TWITCH_CLIENT_ID')
TWITCH_CLIENT_SECRET = os.getenv('TWITCH_CLIENT_SECRET')

DB_PATH = str(ROOT / 'db' / 'gaming_warehouse.db')

In [4]:
#Crear la tabla de hsitorico de reviews
def preparar_tabla_reviews():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS Hist_Steam_Reviews (
            resena_id TEXT PRIMARY KEY,
            juego_id INTEGER,
            resena_texto TEXT,
            recomendado INTEGER, -- (voted_up)
            votos_utiles INTEGER, -- (votes_up)
            votos_graciosos INTEGER, -- (votes_funny)
            puntuacion_ponderada REAL, -- (weighted_vote_score)
            minutos_al_resenar INTEGER, -- (playtime_at_review)
            minutos_totales INTEGER, -- (playtime_forever)
            fecha_creacion_unix INTEGER, -- (timestamp_created)
            autor_num_resenas INTEGER,
            autor_num_juegos INTEGER,
            recibido_gratis INTEGER,
            escrito_acceso_anticipado INTEGER,
            FOREIGN KEY(juego_id) REFERENCES CAT_Juego(juego_id)
        );
    """)
    conn.commit()
    conn.close()

In [5]:
preparar_tabla_reviews()

In [20]:
MAX_REVIEWS_POR_JUEGO = 1000

def obtener_juegos_pendientes():
    conn = sqlite3.connect(DB_PATH)
    query = """
        SELECT 
            j.juego_id, 
            j.id_steam, 
            j.titulo, 
            j.recommendations_count,
            COALESCE(r.reviews_en_bd, 0) as reviews_en_bd
        FROM CAT_Juego j
        LEFT JOIN (
            SELECT juego_id, COUNT(*) as reviews_en_bd 
            FROM Hist_Steam_Reviews 
            GROUP BY juego_id
        ) r ON j.juego_id = r.juego_id
        WHERE j.id_steam IS NOT NULL 
          AND COALESCE(r.reviews_en_bd, 0) < ?
        ORDER BY j.recommendations_count DESC
    """
    df = pd.read_sql_query(query, conn, params=(MAX_REVIEWS_POR_JUEGO,))
    conn.close()
    return df

In [21]:
df_juegos_pendientes=obtener_juegos_pendientes()
df_juegos_pendientes

,juego_id,id_steam,titulo,recommendations_count,reviews_en_bd
0,445,730,Counter-Strike 2,5026951.0,0
1,1,271590,Grand Theft Auto V,1873782.0,0
2,226,578080,PUBG: Battlegrounds,1758437.0,0
3,257,359550,Rainbow Six Siege,1237144.0,0
4,118,105600,Terraria,1207316.0,0
...,...,...,...,...,...
7176,10163,4230,Race: The WTCC Game,NaN,0
7177,10166,615250,M.A.X.: Mechanized Assault & Exploration,NaN,0
7178,10167,359630,Independence War 2: Edge of Chaos,NaN,0
7179,10168,44600,GTR: FIA GT Racing Game,NaN,0
7180,10173,2900,688(I) Hunter/Killer,NaN,0

In [22]:
def descargar_reviews_juego(juego_id, appid, titulo, reviews_en_bd, recommendations_count):
    reviews_objetivo = min(MAX_REVIEWS_POR_JUEGO, recommendations_count)
    reviews_restantes = reviews_objetivo - reviews_en_bd

    if reviews_restantes <= 0:
        return

    print(f"\n{titulo} (AppID: {appid})")
    print(f"  En BD: {reviews_en_bd} | Objetivo: {reviews_objetivo} | Faltan: {reviews_restantes}")

    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA synchronous=NORMAL")
    cursor_bd = conn.cursor()
    cursor_api = '*'
    reviews_acumuladas = 0

    try:
        while reviews_acumuladas < reviews_restantes:
            url = (
                f"https://store.steampowered.com/appreviews/{appid}"
                f"?json=1&filter=recent&language=latam&purchase_type=all"
                f"&cursor={urllib.parse.quote(cursor_api)}&num_per_page=100"
            )

            try:
                res = requests.get(url, timeout=15)
                if res.status_code != 200:
                    print(f"  > HTTP {res.status_code}. Saltando.")
                    break

                data = res.json()
                if not data.get('success') or not data.get('reviews'):
                    print("  > Sin más reseñas en Steam.")
                    break

                batch = data['reviews']

                cursor_bd.executemany(
                    "INSERT OR IGNORE INTO Hist_Steam_Reviews VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                    [
                        (
                            str(r['recommendationid']), juego_id,
                            r['review'],
                            1 if r['voted_up'] else 0,
                            r['votes_up'], r['votes_funny'],
                            float(r['weighted_vote_score']),
                            r['author']['playtime_at_review'],
                            r['author']['playtime_forever'],
                            r['timestamp_created'],
                            r['author']['num_reviews'],
                            r['author']['num_games_owned'],
                            1 if r['received_for_free'] else 0,
                            1 if r['written_during_early_access'] else 0
                        )
                        for r in batch
                    ]
                )
                conn.commit()
                reviews_acumuladas += len(batch)
                print(f"  > {reviews_acumuladas}/{reviews_restantes}")

                nuevo_cursor = data.get('cursor')
                if not nuevo_cursor or nuevo_cursor == cursor_api:
                    print("  > Fin de paginación.")
                    break
                cursor_api = nuevo_cursor

                if len(batch) < 100:
                    print("  > Último lote parcial.")
                    break

                time.sleep(0.5)

            except requests.exceptions.Timeout:
                print("time out, esperar 5 segundos")
                time.sleep(5)
            except Exception as e:
                print(f"  > Error: {e}")
                break
    finally:
        conn.close()

In [24]:
len(df_juegos_pendientes)

7181

In [26]:
total = len(df_juegos_pendientes)

In [27]:
for i, (_, juego) in enumerate(df_juegos_pendientes.iterrows(), 1):
    print(f"[{i}/{total}]", end=' ')
    descargar_reviews_juego(
        juego_id=juego['juego_id'],
        appid=juego['id_steam'],
        titulo=juego['titulo'],
        reviews_en_bd=juego['reviews_en_bd'],
        recommendations_count=juego['recommendations_count']
    )

[1/7181]
Counter-Strike 2 (AppID: 730)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[2/7181]
Grand Theft Auto V (AppID: 271590)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[3/7181]
PUBG: Battlegrounds (AppID: 578080)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[4/7181]
Rainbow Six Siege (AppID: 359550)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[5/7181]
Terraria (AppID: 105600)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[6/7181]
Rust (AppID: 252490)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[7/7181]
Garry's Mod (AppID: 4000)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[8/7181]
Black Myth: Wukong (AppID: 2358720)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[9/7181]
Stardew Valley (AppID: 413150)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[10/7181]
Cyberpunk 2077 (AppID: 1091500)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[11/7181]
Helldivers 2 (AppID: 553850)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[12/7181]
Elden Ring (AppID: 1245620)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[13/7181]
The Witcher 3: Wild Hunt (AppID: 292030)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 699/1000
  > Último lote parcial.
[14/7181]
Red Dead Redemption 2 (AppID: 1174180)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[15/7181]
Left 4 Dead 2 (AppID: 550)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[16/7181]
Euro Truck Simulator 2 (AppID: 227300)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[17/7181]
Baldur's Gate III (AppID: 1086940)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[18/7181]
Phasmophobia (AppID: 739630)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[19/7181]
Dead by Daylight (AppID: 381210)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[20/7181]
Among Us (AppID: 945360)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[21/7181]
Ark: Survival Evolved (AppID: 346110)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[22/7181]
The Forest (AppID: 242760)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[23/7181]
Geometry Dash (AppID: 322170)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[24/7181]
Hollow Knight (AppID: 367520)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[25/7181]
Valheim (AppID: 892970)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[26/7181]
Payday 2 (AppID: 218620)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[27/7181]
Rocket League (AppID: 252950)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[28/7181]
Fall Guys (AppID: 1097150)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[29/7181]
Lethal Company (AppID: 1966720)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[30/7181]
Portal 2 (AppID: 620)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[31/7181]
DayZ (AppID: 221100)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[32/7181]
Dying Light (AppID: 239140)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[33/7181]
Hollow Knight: Silksong (AppID: 1030300)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[34/7181]
Don't Starve Together (AppID: 322330)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[35/7181]
BeamNG.drive (AppID: 284160)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 827/1000
  > Último lote parcial.
[36/7181]
Palworld (AppID: 1623730)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[37/7181]
The Binding of Isaac: Rebirth (AppID: 250900)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[38/7181]
Bloons TD 6 (AppID: 960090)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[39/7181]
Project Zomboid (AppID: 108600)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[40/7181]
Sea of Thieves (AppID: 1172620)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[41/7181]
Raft (AppID: 648800)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[42/7181]
Monster Hunter: World (AppID: 582010)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[43/7181]
Subnautica (AppID: 264710)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[44/7181]
No Man's Sky (AppID: 275850)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[45/7181]
R.E.P.O. (AppID: 3241660)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[46/7181]
Deep Rock Galactic (AppID: 548430)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[47/7181]
People Playground (AppID: 1118200)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 866/1000
  > Último lote parcial.
[48/7181]
Undertale (AppID: 391540)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[49/7181]
Fallout 4 (AppID: 377160)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[50/7181]
Hades (AppID: 1145360)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[51/7181]
Forza Horizon 4 (AppID: 1293830)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[52/7181]
ARC Raiders (AppID: 1808500)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[53/7181]
Dark Souls III (AppID: 374320)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[54/7181]
Hearts of Iron IV (AppID: 394360)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[55/7181]
7 Days to Die (AppID: 251570)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[56/7181]
Sid Meier's Civilization VI (AppID: 289070)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 813/1000
  > Último lote parcial.
[57/7181]
Sons of the Forest (AppID: 1326470)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[58/7181]
Battlefield 6 (AppID: 2807960)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[59/7181]
Hogwarts Legacy (AppID: 990080)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[60/7181]
Schedule I (AppID: 3164500)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[61/7181]
Battlefield 2042 (AppID: 1517290)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[62/7181]
New World: Aeternum (AppID: 1063730)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[63/7181]
Sekiro: Shadows Die Twice (AppID: 814380)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 99/1000
  > Último lote parcial.
[64/7181]
Peak (AppID: 3527290)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[65/7181]
Forza Horizon 5 (AppID: 1551360)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[66/7181]
Vampire Survivors (AppID: 1794680)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[67/7181]
Titanfall 2 (AppID: 1237970)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[68/7181]
Risk of Rain 2 (AppID: 632360)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[69/7181]
Halo: The Master Chief Collection (AppID: 976730)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[70/7181]
Battlefield V (AppID: 1238810)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 890/1000
  > Último lote parcial.
[71/7181]
Arma 3 (AppID: 107410)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 923/1000
  > Último lote parcial.
[72/7181]
Satisfactory (AppID: 526870)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 908/1000
  > Último lote parcial.
[73/7181]
Mount & Blade II: Bannerlord (AppID: 261550)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 423/1000
  > Último lote parcial.
[74/7181]
Cities: Skylines (AppID: 255710)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[75/7181]
Borderlands 2 (AppID: 49520)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[76/7181]
It Takes Two (AppID: 1426210)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[77/7181]
The Elder Scrolls V: Skyrim - Special Edition (AppID: 489830)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[78/7181]
Hunt: Showdown 1896 (AppID: 594650)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[79/7181]
Detroit: Become Human (AppID: 1222140)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[80/7181]
RimWorld (AppID: 294100)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 861/1000
  > Último lote parcial.
[81/7181]
Half-Life 2 (AppID: 220)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[82/7181]
Ultrakill (AppID: 1229490)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[83/7181]
Monster Hunter Wilds (AppID: 2246340)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[84/7181]
Battlefield 1: Revolution (AppID: 1238840)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[85/7181]
Factorio (AppID: 427520)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 617/1000
  > Último lote parcial.
[86/7181]
Doom Eternal (AppID: 782330)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 699/1000
  > Último lote parcial.
[87/7181]
Cuphead (AppID: 268910)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[88/7181]
Slay the Spire (AppID: 646570)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 659/1000
  > Último lote parcial.
[89/7181]
The Elder Scrolls V: Skyrim (AppID: 72850)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 559/1000
  > Último lote parcial.
[90/7181]
Divinity: Original Sin II (AppID: 435150)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 608/1000
  > Último lote parcial.
[91/7181]
Squad (AppID: 393380)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 557/1000
  > Último lote parcial.
[92/7181]
Human: Fall Flat (AppID: 477160)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 930/1000
  > Último lote parcial.
[93/7181]
Clair Obscur: Expedition 33 (AppID: 1903340)
  En BD: 0 | Objetivo: 1000 | Faltan: 1000
  > 100/1000
  > 200/1000
  > 300/1000
  > 400/1000
  > 500/1000
  > 600/1000
  > 700/1000
  > 800/1000
  > 900/1000
  > 1000/1000
[94/7181]
Grand Theft Auto IV (AppID: 12210)

In [30]:
conn = sqlite3.connect(DB_PATH)

resumen = pd.read_sql_query("""
    SELECT 
        COUNT(DISTINCT juego_id) as juegos_con_reviews,
        COUNT(*) as total_reviews,
        ROUND(AVG(reviews_por_juego), 1) as promedio_por_juego,
        MIN(reviews_por_juego) as min_reviews,
        MAX(reviews_por_juego) as max_reviews
    FROM (
        SELECT juego_id, COUNT(*) as reviews_por_juego
        FROM Hist_Steam_Reviews
        GROUP BY juego_id
    )
""", conn)

display(resumen)
conn.close()

,juegos_con_reviews,total_reviews,promedio_por_juego,min_reviews,max_reviews
0,5825,5825,103.0,1,1003

In [31]:
conn = sqlite3.connect(DB_PATH)

distribucion = pd.read_sql_query("""
    SELECT 
        CASE 
            WHEN reviews_por_juego >= 1000 THEN '1000+'
            WHEN reviews_por_juego >= 100  THEN '100-999'
            WHEN reviews_por_juego >= 10   THEN '10-99'
            ELSE '1-9'
        END as rango,
        COUNT(*) as juegos
    FROM (
        SELECT juego_id, COUNT(*) as reviews_por_juego
        FROM Hist_Steam_Reviews
        GROUP BY juego_id
    )
    GROUP BY rango
    ORDER BY rango DESC
""", conn)

conn.close()
display(distribucion)

     rango  juegos
0    1000+     181
1  100-999    1062
2    10-99    2676
3      1-9    1906

In [32]:
conn = sqlite3.connect(DB_PATH)

sin_reviews = pd.read_sql_query("""
    SELECT j.juego_id, j.titulo, j.recommendations_count
    FROM CAT_Juego j
    LEFT JOIN Hist_Steam_Reviews r ON j.juego_id = r.juego_id
    WHERE j.id_steam IS NOT NULL
      AND r.resena_id IS NULL
    ORDER BY j.recommendations_count DESC
""", conn)

conn.close()
print(f"Juegos sin reviews: {len(sin_reviews)}")
display(sin_reviews)

Juegos sin reviews: 1356

,juego_id,titulo,recommendations_count
0,2750,Tomb Raider: Game of the Year Edition,168219.0
1,1419,FIFA 23,123937.0
2,1169,Elden Ring: Shadow of the Erdtree,81654.0
3,18,Batman: Arkham Asylum,58656.0
4,3106,The Elder Scrolls IV: Oblivion - Game of the Y...,42255.0
...,...,...,...
1351,9709,Dead or Alive Xtreme: Venus Vacation,NaN
1352,9972,Chrome: SpecForce,NaN
1353,9978,Total War Battles: Shogun,NaN
1354,10077,Blacklight: Tango Down,NaN
1355,10153,Tom Clancy's Rainbow Six 3: Athena Sword,NaN

In [33]:
with sqlite3.connect(DB_PATH) as conn:
    df = pd.read_sql("""
        SELECT *
        FROM CAT_Juego
        WHERE titulo like "%Batman: Arkham Asylum%"
    """, conn)
    display(df)

,juego_id,id_igdb,id_steam,titulo,categoria,fecha_lanzamiento,resumen,historia,url_portada,puntuacion_igdb,...,hltb_completacionista,steam_price_initial,steam_price_final,steam_discount_percent,metacritic_score,recommendations_count,achievements_count,steam_languages,pc_requirements_json,itad_id_texto
0,18,500,35010,Batman: Arkham Asylum,Juego principal,2009-08-25,Batman: Arkham Asylum is an action-adventure g...,"After the Joker assaults Gotham City Hall, he ...",https://images.igdb.com/igdb/image/upload/t_co...,85.669574,...,None,399.0,399.0,0,91,58656,47,"Inglés, Francés, Alemán, Italiano, Español de ...","{""minimum"": ""<ul class=\""bb_ul\""><li><br><stro...",018d937f-21ee-71f2-aa66-fe39c68e846a
1,914,27862,35140,Batman: Arkham Asylum - Game of the Year Edition,Bundle,2010-03-26,Batman: Arkham Asylum is an action-adventure g...,"After the Joker assaults Gotham City Hall, he ...",https://images.igdb.com/igdb/image/upload/t_co...,86.716050,...,None,399.0,399.0,0,91,58656,47,"Inglés, Francés, Alemán, Italiano, Español de ...","{""minimum"": ""<ul class=\""bb_ul\""><li><br><stro...",018d937f-083f-702e-9c07-4813977240a8

In [60]:
with sqlite3.connect(DB_PATH) as conn:
    df = pd.read_sql("""
        SELECT j.juego_id, j.titulo, j.id_steam, COUNT(r.resena_id) as reviews,fecha_lanzamiento,categoria
    FROM CAT_Juego j
    LEFT JOIN Hist_Steam_Reviews r ON j.juego_id = r.juego_id
    WHERE j.titulo LIKE '%Arkham%city%'
    GROUP BY j.juego_id
    """, conn)
    display(df)

,juego_id,titulo,id_steam,reviews,fecha_lanzamiento,categoria
0,17,Batman: Arkham City,57400.0,2,2011-10-18,Juego principal
1,1016,Batman: Arkham City - Game of the Year Edition,200260.0,1000,2012-05-29,Bundle
2,2291,Batman: Arkham City - Harley Quinn's Revenge,200891.0,0,2012-05-29,Expansión
3,4536,Batman: Return to Arkham - Arkham City,NaN,0,2016-10-17,Remasterización
4,5081,Batman: Arkham City - Catwoman Bundle,NaN,0,2011-10-18,Pack

los juegos faltantes de reviews son aquellos que tiene otras versiones que estana ctivas y se redirigieron ahi, steam quita versiones si ya no se ocuapran

In [58]:
def resumen_final_reviews(cantidad_top=10):
    conn = sqlite3.connect(DB_PATH)
    query = """
    SELECT 
        j.titulo,
        COUNT(r.resena_id) AS total_resenas_descargadas,
        ROUND(AVG(r.recomendado) * 100, 2) || '%' AS recomendado,
        ROUND(AVG(r.minutos_totales / 60.0), 1) AS promedio_horas_jugadas
    FROM Hist_Steam_Reviews r
    JOIN CAT_Juego j ON r.juego_id = j.juego_id
    GROUP BY j.juego_id
    --ORDER BY total_resenas_descargadas DESC
    LIMIT ?;
    """
    df = pd.read_sql_query(query, conn, params=(cantidad_top,))
    conn.close()
    
    display(df.sample(cantidad_top))

In [59]:
resumen_final_reviews(50)

,titulo,total_resenas_descargadas,recomendado,promedio_horas_jugadas
3,The Elder Scrolls V: Skyrim,559,97.5%,283.3
45,Cyberpunk 2077,1000,96.6%,116.0
31,Assassin's Creed IV Black Flag,432,92.36%,61.8
39,Hades,1000,99.7%,67.8
33,Max Payne,156,92.31%,13.6
43,The Elder Scrolls IV: Oblivion,272,94.85%,77.8
7,God of War,1000,99.3%,49.7
20,Hollow Knight,1000,97.7%,77.1
44,Call of Duty: Modern Warfare 2,456,97.59%,39.8
46,Mafia,178,85.39%,20.2
35,Assassin's Creed Brotherhood,200,90.5%,39.9
32,Fallout 3,289,91.0%,45.2
14,BioShock Infinite,1000,96.7%,26.7
18,Tomb Raider,1000,98.4%,21.7
49,Batman: Arkham Knight,1000,97.9%,55.0
21,Elden Ring,1001,97.2%,173.2
27,Grand Theft Auto IV,1000,91.1%,59.8
38,Dragon Age: Origins,54,96.3%,124.3
8,Half-Life 2,1000,98.5%,41.7
22,Doom,1000,98.6%,24.4
16,Mass Effect,84,94.05%,47.4
30,Call of Duty 4: Modern Warfare,334,97.31%,66.2
37,Fallout 4,1000,85.4%,198.8
10,Assassin's Creed II,387,93.28%,35.9
11,Grand Theft Auto: Vice City,388,96.39%,47.0
26,Borderlands 2,1000,79.6%,89.9
23,Dark Souls III,1000,97.4%,122.5
13,Mass Effect 2,48,97.92%,52.2
6,Red Dead Redemption 2,1002,96.51%,116.1
2,Portal 2,1000,99.5%,21.9
29,Mass Effect 3,25,92.0%,40.0
24,Dishonored,750,98.67%,39.9
5,Portal,699,99.43%,11.3
48,Ori and the Blind Forest,113,98.23%,16.7
40,Inside,668,98.2%,6.5
34,Stardew Valley,1002,98.9%,146.7
15,Batman: Arkham City,2,100.0%,78.3
47,NieR: Automata,99,96.97%,46.2
41,Grand Theft Auto III,218,92.2%,29.7
42,Limbo,500,96.4%,7.6
0,Grand Theft Auto V,1000,93.6%,265.0
12,Half-Life,1000,97.8%,28.2
19,Far Cry 3,1000,90.8%,36.2
9,BioShock,400,97.0%,17.3
25,Undertale,1000,69.4%,16.1
17,Fallout: New Vegas,1,100.0%,66.3
4,Grand Theft Auto: San Andreas,990,93.84%,109.3
28,Life is Strange,1000,97.5%,24.8
36,The Walking Dead,800,99.25%,19.9
1,The Witcher 3: Wild Hunt,699,96.85%,121.3

In [61]:
def inspeccionar_resenas(busqueda, es_id=False):
    conn = sqlite3.connect(DB_PATH)
    
    if es_id:
        filtro = "j.juego_id = ?"
        parametro = busqueda
    else:
        filtro = "j.titulo LIKE ?"
        parametro = f"%{busqueda}%"

    query = f"""
    SELECT 
        j.juego_id,
        j.titulo,
        r.recomendado,
        r.minutos_totales / 60 AS horas_jugadas,
        r.votos_utiles,
        r.resena_texto
    FROM Hist_Steam_Reviews r
    JOIN CAT_Juego j ON r.juego_id = j.juego_id
    WHERE {filtro}
    --ORDER BY r.votos_utiles DESC
    --LIMIT 10;
    """
    
    df = pd.read_sql_query(query, conn, params=(parametro,))
    conn.close()
    
    if df.empty:
        print(f"No se encontraron reseñas para: {busqueda}")
    else:
        display(df)

In [63]:
#hAbra que tratar de alguna forma las malas palabras de los jeugos ya que se ve que son creativos con las opiniones
inspeccionar_resenas("counter")

,juego_id,titulo,recomendado,horas_jugadas,votos_utiles,resena_texto
0,445,Counter-Strike 2,1,32,0,esta divertido
1,445,Counter-Strike 2,1,136,0,"Si te odias, este juego es para vos🤙🏽"
2,445,Counter-Strike 2,1,130,0,que buen juego que es\n
3,445,Counter-Strike 2,1,70,0,Todos mis hijos
4,445,Counter-Strike 2,1,442,1,solo quiero el logro por la 1°ra reseña. mucha...
...,...,...,...,...,...,...
3720,3927,Counter-Strike Nexon,1,97,1,Ta chido
3721,3927,Counter-Strike Nexon,0,8,0,full of otakus
3722,3927,Counter-Strike Nexon,1,110,2,En todo el tiempo que lo he jugado jamas me ha...
3723,3927,Counter-Strike Nexon,1,670,0,me guta la variedad de modos de juegos \n
3724,3927,Counter-Strike Nexon,0,652,6,"Tenia mas de 600 horas jugadas, no jugaba hace..."

In [64]:
inspeccionar_resenas("pubg")

,juego_id,titulo,recomendado,horas_jugadas,votos_utiles,resena_texto
0,226,PUBG: Battlegrounds,1,738,0,ta bueno 👍
1,226,PUBG: Battlegrounds,1,751,0,exelente juego
2,226,PUBG: Battlegrounds,1,3,0,Epico siempre y cuando juegues con amigos
3,226,PUBG: Battlegrounds,0,9,0,Es agradable el juego y su gráfica pero lo que...
4,226,PUBG: Battlegrounds,1,10,0,bueb juego
...,...,...,...,...,...,...
997,226,PUBG: Battlegrounds,1,11,0,Tuvo problemas al inicio cuando lo volvieron F...
998,226,PUBG: Battlegrounds,1,679,0,"DE LO MEJOR, MUY REALISTA"
999,226,PUBG: Battlegrounds,1,1091,0,MEDIO PE
1000,226,PUBG: Battlegrounds,1,463,0,Probablemente de los unicos battle royale que ...
1001,226,PUBG: Battlegrounds,1,40,0,la fisica y el realismo ufff bestia